### ISSUE TITLE
Cannot determine consistent method resolution order (MRO) for "OrderedSet" when used with Python 2.7

### ISSUE THREAD

**Issue by gvanrossum** [rominf/ordered-set-stubs#1]
I have installed those stubs for Python 2.7 and am manipulating mypy to find them, by running mypy as follows (`~/v27` is a virtualenv):
```
mypy test.py --python-version 2.7 --python-executable~/v27/bin/python
```
This give me the error
```
/Users/guido/v27/lib/python2.7/site-packages/ordered_set-stubs/__init__.pyi:10: error: Cannot determine consistent method resolution order (MRO) for "OrderedSet"
```
When used with Python 3 all is well.

**Comment by rominf** [comment]
Thank you for bug report, @gvanrossum!

**Comment by gvanrossum** [comment]
Actually it looks like this was a bug in typeshed -- we're fixing it (though you'll have to wait for the next mypy release to get the fix). See https://github.com/python/typeshed/pull/2602.
